### ISSUE TITLE
Cannot parse '123' json string, but {a: '123'} works fine.

### ISSUE THREAD

**Issue by XGHeaven** [XadillaX/fbibik-json#11]
Reproduct code:
```javascript
const fJSON = require('fbbk-json')

console.log(fJSON.parse("{a: '123'}")) // works great
console.log(fJSON.parse("'123'")) // cannot work, an error thrown
```

Error Message:
```javascript
TypeError: Cannot assign to read only property '0' of string ''123''
    at parse (/your/project/path/node_modules/fbbk-json/fjson.js:214:39)
    at Object.g.parse (/your/project/path/node_modules/fbbk-json/fjson.js:353:26)
```

Source Code:
https://github.com/XadillaX/fbibik-json/blob/master/fjson.js#L214
😂

**Comment by XadillaX** [comment]
Could you please make a PR for this issue?

**Comment by XGHeaven** [comment]
ok. Wait a moment. I still on the subway.😗
