### ISSUE TITLE
在多级json字符串中，如果键值对包含“[,],{,}”，会发生解析错误

### ISSUE THREAD

**Issue by plusmancn** [XadillaX/fbibik-json#4]
示例JSON 如下

``` json
{
  "level1": {
    "level2": "with character [,],{,} "
  }
}
```

尝试解析

```
fbbk.parse('{"level1": {"level2": "with character [,],{,} "}');
```

抛出错误

```
Error: Broken JSON object near {"level1": {"level2": "with character [,],{,} "}
    at parse (/Users/plusman/Desktop/dasouche/github/fbibik-json/fjson.js:235:19)
    at Object.g.parse (/Users/plusman/Desktop/dasouche/github/fbibik-json/fjson.js:280:26)
    at Object.<anonymous> (/Users/plusman/Desktop/dasouche/github/fbibik-json/test/bug.js:3:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by XadillaX** [comment]
排查中。

**Comment by XadillaX** [comment]
#5

**Comment by XadillaX** [comment]
merged
